BookProject/BookProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookProject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BookProject/BookProject/Controllers/paperbacksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookProject.Models;

namespace BookProject.Controllers
{
    public class paperbacksController : Controller
    {
        private paperbackDBContext db = new paperbackDBContext();

        //GET: paperbacks

        public ActionResult Index(string searchstring)
        {
            var Paperbacks = from b in db.Paperback
                select b;

            if (!String.IsNullOrEmpty(searchstring))
            {
                Paperbacks = Paperbacks.Where(s =>s.Title.Contains(searchstring));
            }
            return View(Paperbacks);

        }
        //public ActionResult Author(String searchstring)
        //{

        //    var Author = from m in db.Paperback
        //                  select m;

        //    if (!String.IsNullOrEmpty(searchstring))
        //    {
        //        Author = Author.Where(s => s.Author.Contains(searchstring));
        //    }
        //    return View(Author);
        //}



        public ActionResult Reserve()
        {
            return View();
        }


        public ActionResult Search()
        {
            return View(db.Paperback.ToList());
        }

        //public ActionResult Request()
        //{
        //    return View();
        //}
        public ActionResult Request(string searchstring)
        {
            var Paperbacks = from b in db.Paperback
                             select b;

            if (!String.IsNullOrEmpty(searchstring))
            {
                Paperbacks = Paperbacks.Where(s => s.Title.Contains(searchstring));
            }
            return View(Paperbacks);

        }
        //public ActionResult Thanks()
        //{
        //    return View(db.Paperback.ToList());
        //}
        public ActionResult Thanks(string searchstring)
        {
            var Paperbacks = from b in db.Paperback
                             select b;

            if (!String.IsNullOrEmpty(searchstring))
            {
                Paperbacks = Paperbacks.Where(s => s.Title.Contains(searchstring));
            }
            return View(Paperbacks);
        }

        public ActionResult Confirmation()
        {
            return View(db.Paperback.ToList());
        }

        public ActionResult Donate()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Donate([Bind(Include = "ID,ISBNNumber,Title,Author")] paperback paperback)
        {
            if (ModelState.IsValid)
            {
                db.Paperback.Add(paperback);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(paperback);
        }
        // GET: paperbacks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paperback paperback = db.Paperback.Find(id);
            if (paperback == null)
            {
                return HttpNotFound();
            }
            return View(paperback);
        }

        // GET: paperbacks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: paperbacks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ISBNNumber,Title,Author")] paperback paperback)
        {
            if (ModelState.IsValid)
            {
                db.Paperback.Add(paperback);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(paperback);
        }

        // GET: paperbacks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paperback paperback = db.Paperback.Find(id);
            if (paperback == null)
            {
                return HttpNotFound();
            }
            return View(paperback);
        }

        // POST: paperbacks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ISBNNumber,Title,Author")] paperback paperback)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paperback).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(paperback);
        }

        // GET: paperbacks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            paperback paperback = db.Paperback.Find(id);
            if (paperback == null)
            {
                return HttpNotFound();
            }
            return View(paperback);
        }

        // POST: paperbacks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            paperback paperback = db.Paperback.Find(id);
            db.Paperback.Remove(paperback);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookProject/BookProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BookProject/BookProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BookProject/BookProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron" style="background-image: url(../../Images/book2.jpg);">
   
    <h1 style="color:beige">Brytte Book Exchange</h1>
    <p class="lead" style="color:beige">Brytte Book Exchange is a free book exchange site where you can search, donate, or request a book from our inventory for free!</p>
    <p><a href="http://asp.net"></a></p>
</div>

<div class="row">
    <div class="col-md-12">
        <h2>Getting started</h2>
        <p>
           
        <p class="lead">Brytte Book Exchange is a free book exchange site where you can search, donate, or request a book from our inventory for free!</p>
        </p>
        <p><a class="btn btn-default" onclick="location.href= '@Url.Action("Request", "paperbacks")'">Request A Book &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Donate A Book</h2>
        <p>Have a book you'd like to share?  Click on the donate button, and follow the instructions</p>
        <p><a class="btn btn-default" onclick="location.href= '@Url.Action("donate", "paperbacks")'">Donate A Book &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Search For A Book</h2>
        <p>You can easily find the book that you are looking for by clicking the search button.</p>
        <p><a class="btn btn-default" onclick="location.href='@Url.Action("Index","paperbacks")'">Search For A Book &raquo;</a></p>
    </div>
</div>